# Generated by Django 5.2 on 2026-04-28 12:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAccountMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cmr_supplier_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('cmr_supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_mappings', to='accounts.account')),
            ],
            options={
                'db_table': 'supplier_account_mappings',
            },
        ),
    ]
