# Generated by Django 5.2 on 2026-05-29 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_supplieraccountmapping'),
        ('purchases', '0002_bill_supplier_nullable_billline_account_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='default_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_suppliers', to='accounts.account'),
        ),
    ]
