# Generated by Django 5.2 on 2026-06-03 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_alter_journalentry_source'),
        ('purchases', '0005_backfill_bill_vat_quarter'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillPaymentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('matched_by', models.CharField(blank=True, default='', max_length=200)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='purchases.bill')),
                ('journal_entry_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_payment_links', to='journals.journalentryline')),
            ],
            options={
                'db_table': 'bill_payment_links',
                'unique_together': {('bill', 'journal_entry_line')},
            },
        ),
    ]
