# Generated by Django 4.2.30 on 2026-06-25 08:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_supplieraccountmapping'),
        ('core', '0005_companysettings_logos'),
        ('purchases', '0006_billpaymentlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_lines', to='accounts.account')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.expense')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_lines', to='core.taxcode')),
            ],
            options={
                'db_table': 'expense_lines',
                'ordering': ['id'],
            },
        ),
    ]
