# Generated by Django 5.2 on 2026-06-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_invoiceline_text_hidden_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Purchase price — drives the billed line amount', max_digits=15),
        ),
    ]
