# Generated by Django 5.2 on 2026-06-20 12:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_supplieraccountmapping'),
        ('journals', '0006_alter_journalentry_source'),
        ('payroll', '0002_holidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'public_holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cnss_number', models.CharField(blank=True, default='', max_length=50)),
                ('cin', models.CharField(blank=True, default='', help_text="Carte d'identité nationale", max_length=20)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('gross_salary', models.DecimalField(decimal_places=2, help_text='Monthly gross salary in MAD', max_digits=12)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=50)),
                ('annual_leave_days', models.DecimalField(decimal_places=1, default=18, help_text='Annual paid leave entitlement in days', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salary_account', models.ForeignKey(help_text='Salary expense account (572201-572213)', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='accounts.account')),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['employee_number'],
            },
        ),
        migrations.CreateModel(
            name='LeaveEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('leave_type', models.CharField(choices=[('annual', 'Annual'), ('sick', 'Sick'), ('unpaid', 'Unpaid'), ('other', 'Other')], default='annual', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_entries', to='payroll.employee')),
            ],
            options={
                'db_table': 'leave_entries',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(help_text='1-12')),
                ('run_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cnss_employee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cnss_employer', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_ir', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to='journals.journalentry')),
            ],
            options={
                'db_table': 'payroll_runs',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cnss_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cnss_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ir_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_lines', to='payroll.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payrollrun')),
            ],
            options={
                'db_table': 'payroll_lines',
                'ordering': ['employee__employee_number'],
            },
        ),
        migrations.CreateModel(
            name='HolidayWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_work', to='payroll.employee')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='payroll.publicholiday')),
            ],
            options={
                'db_table': 'holiday_work',
                'unique_together': {('holiday', 'employee')},
            },
        ),
    ]
