# Generated by Django 5.2 on 2026-04-27 10:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('cmr_invoice', 'CMR Invoice'), ('cmr_payment', 'CMR Payment'), ('expense', 'Expense'), ('bank', 'Bank')], default='manual', max_length=20)),
                ('source_id', models.CharField(blank=True, default='', max_length=100)),
                ('is_posted', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'journal_entries',
                'ordering': ['-date', '-entry_number'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='MAD', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('base_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('base_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounts.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='journals.journalentry')),
            ],
            options={
                'db_table': 'journal_entry_lines',
                'ordering': ['id'],
            },
        ),
    ]
