# Generated by Django 5.2 on 2026-04-28 21:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_supplieraccountmapping'),
        ('journals', '0002_alter_journalentry_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDescriptionMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description_key', models.CharField(db_index=True, max_length=500, unique=True)),
                ('example_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_mappings', to='accounts.account')),
            ],
            options={
                'db_table': 'bank_description_mappings',
            },
        ),
    ]
