# Generated by Django 5.2 on 2026-05-01 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_supplieraccountmapping'),
        ('core', '0002_initial'),
        ('journals', '0005_alter_journalentry_source'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='sales.invoice'),
        ),
        migrations.AddField(
            model_name='document',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='journals.journalentry'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_as_bank', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sales.customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='journals.journalentry'),
        ),
        migrations.AddField(
            model_name='payment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='purchases.supplier'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.payment'),
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='sales.customer'),
        ),
        migrations.AddField(
            model_name='projecttransaction',
            name='journal_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_transactions', to='journals.journalentryline'),
        ),
        migrations.AddField(
            model_name='projecttransaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.project'),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_codes', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='projecttransaction',
            unique_together={('project', 'journal_line')},
        ),
    ]
